# Линейная алгебра. Практическое задание Урок 5 Сингулярное разложение матриц

In [13]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)
#Найдите посредством NumPy SVD для матрицы:
A = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])
#представление матрицы А в виде: A=UDV^T - называется сингулярным разложением
U, s, W = np.linalg.svd(A)
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s
SVD = np.dot(np.dot(U, D), W)
print('SVD для матрицы А: ', A, sep='\n')
print('является: ', SVD, sep='\n')



SVD для матрицы А: 
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]
является: 
[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1. -0.]]


In [16]:
#Для матрицы из предыдущего задания найдите евклидову норму
print('Евклидова норма для матрицы A:', np.linalg.norm(A, ord = 2))

Евклидова норма для матрицы A: 8.824868854820444


In [17]:
#Для матрицы из предыдущего задания найдите норму Фробениуса
print('Норма Фробениуса для матрицы A:', np.linalg.norm(A, ord = 'fro'))

Норма Фробениуса для матрицы A: 11.045361017187261
